#!/bin/bash 

REFDIR=$1
TAG=$2
GFF=$3
FA=$4

##   the following directory structure is implied: 
##   $REFDIR/Assemblies 
##   $REFDIR/bowtie2
##   $REFDIR/RSEM
##   $REFDIR/kallisto

##   1) check what sort of GFF file you're dealing with (if it has ^> in it)
##   we assume there's always ncRNA - if that's empty, scripts should still work 
 
PP1=`grep -P "^>" $GFF`
PP2=`grep -P "##FASTA" $GFF`

if [[ $PP1 != "" && $PP2 != "" && $FA == "" ]]
then 
  echo "The GFF file provided was identified as generated by Prokka! Continuing.." 
  N_CDS=`grep -c -P "\tCDS\t" $GFF`
  N_NCR=`grep -c -P "\tmisc_RNA\t" $GFF`
  echo "Found $N_CDS protein-coding (CDS) and $N_NCR non-coding RNA (misc_RNA) features!"
  grep -P "\tCDS\t" $GFF > $TAG.CDS.gff
  grep -P "\tmisc_RNA\t" $GFF | sed "s/misc_RNA/ncRNA/g" | \
  perl -ne 'm/.*;product=(.*)$/; $n=$1; s/inference=/Name=$n;inference=/; print' > $TAG.ncRNA.gff 
  ## make a special GFF file with all features collated into "gene", because reasons 
  sed "s/\tCDS\t/\tgene\t/g"   $TAG.CDS.gff   >  $TAG.gene.gff
  sed "s/\tncRNA\t/\tgene\t/g" $TAG.ncRNA.gff >> $TAG.gene.gff

  grep -v -P "^#" $GFF | grep -v "\t" > $TAG.genome.fa
  echo "Files $TAG.genome.fa, $TAG.CDS.gff, $TAG.ncRNA.gff, and $TAG.gene.gff successfully generated."
elif [[ $PP1 == "" && $PP2 == "" && $FA != "" ]]
then
  echo "Custom GFF/FA files provided! Continuing.."
  N_CDS=`grep -c -P "\tCDS\t" $GFF`
  N_NCR=`grep -c -P "\tmisc_RNA\t|\tncRNA\t" $GFF`
  echo "Found $N_CDS protein-coding (CDS) and $N_NCR non-coding RNA (misc_RNA/ncRNA) features!"
  grep -P "\tCDS\t" $GFF > $TAG.CDS.gff
  grep -P "\tmisc_RNA\t|\tncRNA\t" $GFF | sed "s/misc_RNA/ncRNA/g" > $TAG.ncRNA.gff 
  sed "s/\tCDS\t/\tgene\t/g"   $TAG.CDS.gff   >  $TAG.gene.gff
  sed "s/\tncRNA\t/\tgene\t/g" $TAG.ncRNA.gff >> $TAG.gene.gff

  cp $FA $TAG.genome.fa
  echo "Files $TAG.genome.fa, $TAG.CDS.gff, $TAG.ncRNA.gff, and $TAG.gene.gff successfully generated."
else
  echo "ERROR: Either provide a Prokka-style GFF file, or a custom GFF/FA pair!"
fi 

##   3) make 3-col file: locus tag, gene name, and type (CDS/ncRNA). 

cat $TAG.CDS.gff $TAG.ncRNA.gff | \
perl -ne '$n; $id; @t=split/\t/; $t[8]=~m/^ID=(.*?);.*/; $id=$1; if ($t[8]=~m/.*;Name=(.*?);.*/) {$n=$1} else {$n=$id}; print "$id\t$n\t$t[2]\n"' > $TAG.3col 

##   4) run prokka on genome, find all of the rRNA sequences 

source activate prokka 
prokka --quiet --cpus 16 --outdir $TAG.prokka --prefix $TAG.prokka --locustag $TAG $TAG.genome.fa
source deactivate

grep -P "\ttRNA\t" $TAG.prokka/$TAG.prokka.gff | awk '{print $1"\t"$4-1"\t"$5"\ttRNA."NR"\t.\t"$7}' > $TAG.tRNA.bed
grep -P "\trRNA\t" $TAG.prokka/$TAG.prokka.gff | awk '{print $1"\t"$4-1"\t"$5"\trRNA."NR"\t.\t"$7}' > $TAG.rRNA.bed
bedtools getfasta -name -s -fi $TAG.genome.fa -bed $TAG.tRNA.bed -fo $TAG.tRNA.fa
bedtools getfasta -name -s -fi $TAG.genome.fa -bed $TAG.rRNA.bed -fo $TAG.rRNA.fa
rm -rf $TAG.prokka $TAG.tRNA.bed $TAG.rRNA.bed

##   5) *chrom.size reference 

samtools faidx $TAG.genome.fa
cut -f 1,2 $TAG.genome.fa.fai > $TAG.chrom.sizes 

##   6) bowtie2 reference 
bowtie2-build --quiet $TAG.genome.fa $TAG
bowtie2-build --quiet $TAG.tRNA.fa $TAG.tRNA
bowtie2-build --quiet $TAG.rRNA.fa $TAG.rRNA 

##   8) rsem/kallisto reference - skip this for now

##   9) copy to appropriate locations
mv *bt2 $REFDIR/bowtie2
mv $TAG.genome.fa $TAG.tRNA.fa $TAG.rRNA.fa $REFDIR/Assemblies
mv $TAG.gene.gff $TAG.CDS.gff $TAG.ncRNA.gff $REFDIR/Assemblies
mv $TAG.genome.fa.fai $TAG.chrom.sizes $TAG.3col $REFDIR/Assemblies
